info:
  version: 1.0-SNAPSHOT
  stage: test

logging:
  file: target/boot-admin-sample.log


spring:

  application:
    name: learn2rank-admin

  datasource:
    url: jdbc:h2:~/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

  boot:
    admin:
      url: http://localhost:8080
      username: admin
      password: admin123

  cloud:
    config:
      enabled: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create


endpoints:
  health:
    sensitive: false